### ISSUE TITLE
Order of node, edge, and link convolutions in ArrangementNet

### ISSUE THREAD

**Issue by JY251** [zssjh/ArrangementNet#4]
I have a question on the following part of the code: https://github.com/zssjh/ArrangementNet/blob/77001ca30e794d529c9652ea3a9f14e8fd36677b/src/model.py#L342-L346

In the section 4.3 of the paper "ArrangementNet: Learning Scene Arrangements for Vectorized Indoor Scene Modeling. (SIGGRAPH 2023)", it is mentioned that the convolutions in the GNN are dones in the order of **node convolution**, **edge convolution**, and **link convolution**. 

However, I guess the order is **node convolution**, **link convolution**, and **edge convolution** in the code. 
I guess `edge_node_conv` indicates **link convolution** in the code because it only takes the edge features as input while `edge_conv` takes both the edge and node features as input.   
(Looking at the paper, when calculating Eq (4), both the node and edge features are used so I have regarded `edge_conv` as edge convolution. On the other hand, Eq (5) only uses the edge features so I have regarded `edge_node_conv`  as link convolution.)

I will be grateful if you could confirm my understanding.
I will apologize if I have misunderstood the paper or the code. Thank you.

**Comment by zssjh** [comment]
yes, you're right.
